spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: 667192
    url: jdbc:mysql://localhost:3306/mobilele_db?allowPublicKeyRetrieval=true&useSSL=false&createDatabaseIfNotExist=true
  #      &serverTimezone=UTC
  jpa:
    hibernate:
      #        ddl-auto: update
      ddl-auto: create-drop
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
  mvc:
    hiddenmethod:
      filter:
        enabled: true
